/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import BD.Bbdd;
import Modelo.Usuario;
import java.awt.Color;
import com.toedter.calendar.JDateChooser;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author DAM2_06
 */
public class AgregarNuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AgregarNuevoUsuario
     */
    private boolean flag = false;

    public AgregarNuevoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_nuevo_usuario = new javax.swing.JLabel();
        texto_usuario_nuevo = new javax.swing.JLabel();
        texto_contrasena_nueva = new javax.swing.JLabel();
        texto_confirmar_contrasena_nueva = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        agregar_datos_nuevo = new javax.swing.JLabel();
        texto_nombre_nuevo = new javax.swing.JLabel();
        texto_apellido_nuevo = new javax.swing.JLabel();
        texto_fecha_nuevo = new javax.swing.JLabel();
        texto_correo_nuevo = new javax.swing.JLabel();
        boton_volver = new javax.swing.JButton();
        boton_agregar = new javax.swing.JButton();
        usuario_nuevo = new javax.swing.JTextField();
        nombre_nuevo = new javax.swing.JTextField();
        apellido_nuevo = new javax.swing.JTextField();
        correo_nuevo = new javax.swing.JTextField();
        contrasena_nueva = new javax.swing.JPasswordField();
        confirmar_contrasena_nueva = new javax.swing.JPasswordField();
        texto_existe_usuario = new javax.swing.JLabel();
        fecha_nuevo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        info_nuevo_usuario.setText("Por favor, introduzca la información del nuevo usuario:");

        texto_usuario_nuevo.setText("Usuario");

        texto_contrasena_nueva.setText("Contraseña");

        texto_confirmar_contrasena_nueva.setText("Confirmar contraseña");

        agregar_datos_nuevo.setText("Agregar datos opcionales del nuevo usuario:");

        texto_nombre_nuevo.setText("Nombre");

        texto_apellido_nuevo.setText("Apellidos");

        texto_fecha_nuevo.setText("Fecha de nacimiento");

        texto_correo_nuevo.setText("Correo");

        boton_volver.setText("Volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        boton_agregar.setText("Agregar");
        boton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregarActionPerformed(evt);
            }
        });

        usuario_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_nuevoActionPerformed(evt);
            }
        });

        correo_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correo_nuevoKeyReleased(evt);
            }
        });

        confirmar_contrasena_nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_contrasena_nuevaActionPerformed(evt);
            }
        });

        texto_existe_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                texto_existe_usuarioMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(info_nuevo_usuario)
                .addGap(75, 75, 75))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregar_datos_nuevo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto_nombre_nuevo)
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(correo_nuevo)
                                    .addComponent(apellido_nuevo)
                                    .addComponent(nombre_nuevo)
                                    .addComponent(fecha_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texto_contrasena_nueva)
                            .addComponent(texto_confirmar_contrasena_nueva)
                            .addComponent(texto_usuario_nuevo))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario_nuevo)
                            .addComponent(contrasena_nueva)
                            .addComponent(confirmar_contrasena_nueva, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_existe_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(texto_apellido_nuevo)
                                .addComponent(texto_fecha_nuevo)
                                .addComponent(texto_correo_nuevo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(info_nuevo_usuario)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_usuario_nuevo)
                    .addComponent(usuario_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_contrasena_nueva)
                    .addComponent(contrasena_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_confirmar_contrasena_nueva)
                    .addComponent(confirmar_contrasena_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar_datos_nuevo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_nombre_nuevo)
                    .addComponent(nombre_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_apellido_nuevo)
                    .addComponent(apellido_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texto_fecha_nuevo)
                    .addComponent(fecha_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_correo_nuevo)
                    .addComponent(correo_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(texto_existe_usuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_volver)
                    .addComponent(boton_agregar))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuario_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_nuevoActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed

    private void boton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregarActionPerformed

        String us = usuario_nuevo.getText();
        String contrasena = String.valueOf(contrasena_nueva.getPassword());
        String nombre = nombre_nuevo.getText();
        String apellidos = apellido_nuevo.getText();
        Date fecha_nac = fecha_nuevo.getDate();
        String correo = correo_nuevo.getText();

        if (Bbdd.verificarUsuario(usuario_nuevo.getText())) {
            texto_existe_usuario.setText("Ya existe un usuario con ese nombre");
            return;
        }

        if (!confirmar_contrasena_nueva()) {
            texto_existe_usuario.setText("Las contraseñas no coinciden");
            return;
        }

        if (flag) {
            texto_existe_usuario.setText("El correo no es válido");
            return;
        }

        if (nombre.isBlank()) {
            nombre_nuevo.setBorder(new LineBorder(Color.RED));
            return;
        }
        nombre_nuevo.setBorder(new LineBorder(Color.GRAY));
        if (apellidos.isBlank()) {
            apellido_nuevo.setBorder(new LineBorder(Color.RED));
            return;
        }
        apellido_nuevo.setBorder(new LineBorder(Color.GRAY));
        
        if (correo.isBlank()) {
            correo_nuevo.setBorder(new LineBorder(Color.RED));
            return;
        }
        correo_nuevo.setBorder(new LineBorder(Color.GRAY));

        Bbdd.registrarUsuario(new Usuario(us, contrasena, nombre, apellidos, fecha_nac, correo));  // Si no existe, registrar el usuario
        texto_existe_usuario.setText("Usuario registrado correctamente");


    }//GEN-LAST:event_boton_agregarActionPerformed

    public boolean confirmar_contrasena_nueva() {
        String contrasena = String.valueOf(contrasena_nueva.getPassword());
        String confirmar_contrasena = String.valueOf(confirmar_contrasena_nueva.getPassword());

        // Verificar si las contraseñas son iguales
        if (!confirmar_contrasena.equals(contrasena)) {
            // Si no son iguales, establecer el borde rojo
            confirmar_contrasena_nueva.setBorder(new LineBorder(Color.RED));
            return false;
        } else {
            confirmar_contrasena_nueva.setBorder(new LineBorder(Color.GRAY));
            return true;
        }
    }
    private void confirmar_contrasena_nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_contrasena_nuevaActionPerformed

    }//GEN-LAST:event_confirmar_contrasena_nuevaActionPerformed

    private void texto_existe_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_existe_usuarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_existe_usuarioMouseReleased

    private void correo_nuevoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correo_nuevoKeyReleased
        String regex = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        Border borderRojo = BorderFactory.createLineBorder(Color.RED, 1);
        Border borderNormal = BorderFactory.createLineBorder(Color.GRAY, 1);
        if (!correo_nuevo.getText().matches(regex)) {
            flag = true;
            correo_nuevo.setBorder(borderRojo);
            return;
        }
        flag = false;
        correo_nuevo.setBorder(borderNormal);

    }//GEN-LAST:event_correo_nuevoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar_datos_nuevo;
    private javax.swing.JTextField apellido_nuevo;
    private javax.swing.JButton boton_agregar;
    private javax.swing.JButton boton_volver;
    private javax.swing.JPasswordField confirmar_contrasena_nueva;
    private javax.swing.JPasswordField contrasena_nueva;
    private javax.swing.JTextField correo_nuevo;
    private com.toedter.calendar.JDateChooser fecha_nuevo;
    private javax.swing.JLabel info_nuevo_usuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre_nuevo;
    private javax.swing.JLabel texto_apellido_nuevo;
    private javax.swing.JLabel texto_confirmar_contrasena_nueva;
    private javax.swing.JLabel texto_contrasena_nueva;
    private javax.swing.JLabel texto_correo_nuevo;
    private javax.swing.JLabel texto_existe_usuario;
    private javax.swing.JLabel texto_fecha_nuevo;
    private javax.swing.JLabel texto_nombre_nuevo;
    private javax.swing.JLabel texto_usuario_nuevo;
    private javax.swing.JTextField usuario_nuevo;
    // End of variables declaration//GEN-END:variables
}
