/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import BD.Bbdd;
import static BD.Bbdd.modificarUsuario;
import Modelo.Usuario;

/**
 *
 * @author DAM2_06
 */
public class NuevaContrasena extends javax.swing.JFrame {

    /**
     * Creates new form nuevaContrasena
     */
    private String usuario;

    public NuevaContrasena(String user) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        usuario = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_contr_antigua = new javax.swing.JLabel();
        txt_contr_nueva = new javax.swing.JLabel();
        txt_confirmacion = new javax.swing.JLabel();
        mensaje_cambio_contr = new javax.swing.JLabel();
        contr_antigua = new javax.swing.JPasswordField();
        contr_nueva = new javax.swing.JPasswordField();
        confirm_contr_nueva = new javax.swing.JPasswordField();
        boton_mostrar_confirmacion = new javax.swing.JCheckBox();
        boton_volver = new javax.swing.JButton();
        boton_mostrar_contr_nueva = new javax.swing.JCheckBox();
        boton_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_contr_antigua.setText("Contraseña antigua:");

        txt_contr_nueva.setText("Contraseña nueva:");

        txt_confirmacion.setText("Confirmar contraseña nueva:");

        boton_mostrar_confirmacion.setText("Mostrar");
        boton_mostrar_confirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrar_confirmacionActionPerformed(evt);
            }
        });

        boton_volver.setText("Volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        boton_mostrar_contr_nueva.setText("Mostrar");
        boton_mostrar_contr_nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrar_contr_nuevaActionPerformed(evt);
            }
        });

        boton_modificar.setText("Modificar contraseña");
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(mensaje_cambio_contr, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_confirmacion)
                                .addGap(45, 45, 45)
                                .addComponent(confirm_contr_nueva))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_contr_antigua)
                                    .addComponent(txt_contr_nueva))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contr_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contr_antigua, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_mostrar_confirmacion)
                            .addComponent(boton_mostrar_contr_nueva)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(boton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mensaje_cambio_contr)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contr_antigua)
                    .addComponent(contr_antigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contr_nueva)
                    .addComponent(contr_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_mostrar_contr_nueva))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirmacion)
                    .addComponent(confirm_contr_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_mostrar_confirmacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_volver)
                    .addComponent(boton_modificar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed

    private void boton_mostrar_contr_nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrar_contr_nuevaActionPerformed
        if (boton_mostrar_contr_nueva.isSelected()) {
            contr_nueva.setEchoChar((char) 0);
        } else {
            contr_nueva.setEchoChar('*');
        }
    }//GEN-LAST:event_boton_mostrar_contr_nuevaActionPerformed

    private void boton_mostrar_confirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrar_confirmacionActionPerformed
        if (boton_mostrar_confirmacion.isSelected()) {
            confirm_contr_nueva.setEchoChar((char) 0);
        } else {
            confirm_contr_nueva.setEchoChar('*');
        }
    }//GEN-LAST:event_boton_mostrar_confirmacionActionPerformed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        Usuario u = Bbdd.seleccionarUsuario(usuario);
        String ant_password = String.valueOf(contr_antigua.getPassword());
        String password = String.valueOf(contr_nueva.getPassword());
        String conf_password = String.valueOf(confirm_contr_nueva.getPassword());

        mensaje_cambio_contr.setText(u.getContrasena() + "-----------");
        System.out.println(u.getContrasena());
        if (!ant_password.equals(u.getContrasena())) {
            mensaje_cambio_contr.setText("La contraseña no coincide");
            return;
        }

        if (!password.equals(conf_password)) {
            mensaje_cambio_contr.setText("Las contraseñas no coinciden");
            return;
        }
        u.setContrasena(password);
        modificarUsuario(u);
        mensaje_cambio_contr.setText("Contraseña cambiada correctamente");
    }//GEN-LAST:event_boton_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaContrasena("").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_modificar;
    private javax.swing.JCheckBox boton_mostrar_confirmacion;
    private javax.swing.JCheckBox boton_mostrar_contr_nueva;
    private javax.swing.JButton boton_volver;
    private javax.swing.JPasswordField confirm_contr_nueva;
    private javax.swing.JPasswordField contr_antigua;
    private javax.swing.JPasswordField contr_nueva;
    private javax.swing.JLabel mensaje_cambio_contr;
    private javax.swing.JLabel txt_confirmacion;
    private javax.swing.JLabel txt_contr_antigua;
    private javax.swing.JLabel txt_contr_nueva;
    // End of variables declaration//GEN-END:variables
}
